# Generated by Django 2.2.3 on 2019-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('number', models.CharField(max_length=10, verbose_name='Street number')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=35, verbose_name='State')),
                ('zipcode', models.CharField(max_length=25, verbose_name='Zip code')),
            ],
        ),
    ]
